swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # ... existing paths ...

  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Get All Transactions
      description: API for fetching all transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: List of all transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Get Specific Transaction
      description: API for fetching a specific transaction by its ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: The ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    put:
      tags:
        - Transaction Module
      summary: Update Transaction
      description: API for updating a transaction's category and notes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: The ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Transaction category and notes to update
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Transaction ID or Fields
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

  /transaction/{transactionId}/details: # New endpoint for getting transaction details
    get:
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: API for fetching details of a specific transaction by its ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: The ID of the transaction to retrieve details for
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

  /transaction/{transactionId}/delete: # New endpoint for deleting a transaction
    delete:
      tags:
        - Transaction Module
      summary: Delete Transaction
      description: API for deleting a specific transaction by its ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: The ID of the transaction to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        '204':
          description: Transaction deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  # ... existing definitions ...

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Category of the transaction
      note:
        type: string
        description: Note added to the transaction

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      category:
        type: string
        description: Category of the transaction
      note:
        type: string
        description: Note added to the transaction
      # ... other properties of Transaction
